hasResponseItem:
  responses:
    200:
      body:
        application/json:
          type: <<typeName>>

hasNotFound:
  responses:
    404:
      body:
        application/json:
          type: Error
