type:
   enum: ["OWNED_BY_SELF_OR_SPOUSE", "OWNED_BY_PARENT_OR_SIBLING", "RENTED_AND_STAYING_WITH_FAMILY", "RENTED_AND_STAYING_WITH_FRIENDS",
  "RENTED_AND_STAYING_ALONE", "PAYING_GUEST", "HOSTEL", "COMPANY_PROVIDED"]
