type: object
properties:
  employmentType?: EmploymentType
  totalWorkExperience?: number
  salaryBankAccount?: Bank
  employer?: Company
  dateOfJoining?: date-only
  designation?: string
  netMonthlySalary? : Currency
  avgMonthlyIncentives?: Currency
  annualBonus?: Currency
  profitAfterTax?: Currency