type: object
properties:
  id?:
    type: number
    format: int64
  userName: string
  loginType: LoginType
  contactDetail?: ContactDetail
  employmentDetail?: EmploymentDetail
  personalInformation?: PersonalInformation
  uniquePersonIdentifiers?: UniquePersonIdentifier[]


