type: object
properties:
  firstName?: string
  middleName?: string
  lastName?: string
  dob?: date-only
  gender?: Gender
  maritalStatus?: MaritalStatus
  highestEducationalQualification?: HighestEducationalQualification